### ISSUE TITLE
Using the following cache for assets configuration:

### ISSUE THREAD

**Issue by mavarazy** [thankyo/backend#65]
https://sentry.io/happiness-lab-inc/loveit-backend/issues/430364212/

```
Stacktrace (most recent call first):

    at controllers.AssetsConfiguration$.logAssetsConfiguration(Assets.scala:275)
    at controllers.AssetsConfiguration$.fromConfiguration(Assets.scala:262)
    at controllers.AssetsConfigurationProvider.get(Assets.scala:285)
    at controllers.AssetsConfigurationProvider.get(Assets.scala:284)
    at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
    at com.google.inject.internal.BoundProviderFactory.provision(BoundProviderFactory.java:72)
    at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:61)
    at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:62)

Using the following cache for assets configuration:
	 enabledCaching = true
	 enabledCacheControl = true
	 defaultCacheControl = public, max-age=3600
	 aggressiveCacheControl = public, max-age=31536000, immutable
	 configuredCacheControl:


```

**Comment by mavarazy** [comment]
Seems to be fixed
