### ISSUE TITLE
Illegal header: Illegal 'content-type' header: Invalid input ',', expected tchar, OWS, ws or 'EOI...

### ISSUE THREAD

**Issue by mavarazy** [thankyo/backend#66]
https://sentry.io/happiness-lab-inc/loveit-backend/issues/440576088/

```
Stacktrace (most recent call first):

    at akka.event.slf4j.Slf4jLogger$$anonfun$receive$1.$anonfun$applyOrElse$2(Slf4jLogger.scala:75)
    at akka.event.slf4j.Slf4jLogger.withMdc(Slf4jLogger.scala:100)
    at akka.event.slf4j.Slf4jLogger$$anonfun$receive$1.applyOrElse(Slf4jLogger.scala:75)
    at akka.actor.Actor.aroundReceive(Actor.scala:517)
    at akka.actor.Actor.aroundReceive$(Actor.scala:515)
    at akka.event.slf4j.Slf4jLogger.aroundReceive(Slf4jLogger.scala:54)
    at akka.actor.ActorCell.receiveMessage(ActorCell.scala:527)
    at akka.actor.ActorCell.invoke(ActorCell.scala:496)

Illegal header: Illegal 'content-type' header: Invalid input ',', expected tchar, OWS, ws or 'EOI' (line 1, column 17): application/json, application/json
                ^
```

**Comment by mavarazy** [comment]
Seems to be alright now
