### ISSUE TITLE
IllegalArgumentException: http:www.my30dc.com could not be parsed into a proper Uri, missing host

### ISSUE THREAD

**Issue by mavarazy** [thankyo/backend#72]
https://sentry.io/happiness-lab-inc/loveit-backend/issues/532292917/

```
UnexpectedException: Unexpected exception[IllegalArgumentException: Invalid URL http:www.my30dc.com]
    at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:251)
    at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:182)
    at com.clemble.loveit.common.controller.ErrorHandler.onServerError(ErrorHandler.scala:40)
    at play.core.server.AkkaHttpServer$$anonfun$2.applyOrElse(AkkaHttpServer.scala:343)
    at play.core.server.AkkaHttpServer$$anonfun$2.applyOrElse(AkkaHttpServer.scala:341)
...
(14 additional frame(s) were not displayed)

IllegalArgumentException: Invalid URL http:www.my30dc.com
    at play.api.libs.ws.ahc.StandaloneAhcWSClient.validate(StandaloneAhcWSClient.scala:84)
    at play.api.libs.ws.ahc.StandaloneAhcWSClient.url(StandaloneAhcWSClient.scala:42)
    at play.api.libs.ws.ahc.AhcWSClient.url(AhcWSClient.scala:35)
    at com.clemble.loveit.thank.service.SimpleProjectEnrichService.enrichDescription(ProjectEnrichService.scala:97)
    at com.clemble.loveit.thank.service.SimpleProjectEnrichService.doEnrich(ProjectEnrichService.scala:122)
...
(17 additional frame(s) were not displayed)

IllegalArgumentException: http:www.my30dc.com could not be parsed into a proper Uri, missing host
    at play.shaded.ahc.org.asynchttpclient.uri.Uri.create(Uri.java:43)
    at play.shaded.ahc.org.asynchttpclient.uri.Uri.create(Uri.java:32)
    at play.api.libs.ws.ahc.StandaloneAhcWSClient.validate(StandaloneAhcWSClient.scala:81)
    at play.api.libs.ws.ahc.StandaloneAhcWSClient.url(StandaloneAhcWSClient.scala:42)
    at play.api.libs.ws.ahc.AhcWSClient.url(AhcWSClient.scala:35)
...
(19 additional frame(s) were not displayed)



! @77jnkf6o6 - Internal server error, for (GET) [/api/v1/thank/enrich?url=http:www.my30dc.com] ->
 
```

**Comment by mavarazy** [comment]
Can't connect to this in any state, so I'll just leave it be, with no further explanations
